debug: false

logging:
  level:
    org:
      hibernate:
        type: trace
spring:
  jpa:
    hibernate:
      ddl-auto: update

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL;
    username: sa
    password: 123456

  redis:
    host: localhost
    port: 6379
    database: 2

upload-directory: './files'

security:
  lock:
    enabled: true
    max-try-times: 5
    lock-duration: 30m
  password-expire:
    enabled: true
    lifetime-duration: 90d
